### ISSUE TITLE
Large screens should see multiple project cards per row

### ISSUE THREAD

**Issue by chrisvogt** [godaddy/godaddy.github.io#17]
As of #16 the [featured projects page](https://godaddy.github.io/featured-projects/) renders projects as [Materialize cards](https://materializecss.com/cards.html). Based on the content currently rendering into these cards we should be able to safely render multiple cards per row on large screens. 

### Getting started on this issue

It is straightforward to implement this in the _featured-projects.html_ template using the [Materialize grid system](https://materializecss.com/grid.html):

```liquid
<div class="col s12 l6">
  {% include component/project-card.html project=project %}
</div>
```

This updates project cards to render two per row, however the cards will vary in height based on the card content (_see "jumbled cards" below_). To complete this issue, cards should render two per row and uniform in height.

### Implementation and design thoughts

One way to do this is with the `min-height` technique, demonstrated in the examples below. This is done by setting a minimum height on the `.card-content`. This is a fragile solution because introducing an unexpectedly verbose project has potential to stretch that card taller than the others.

Materialize may provide a solution; using custom JavaScript or jQuery may be necessary; or, there might even be a good CSS-based way to achieve this.

##### Jumbled cards

![jumbled-cards](https://user-images.githubusercontent.com/1934719/39565800-3e597c68-4e6e-11e8-99c6-4ba4dc48db2c.png)

##### "min-height" technique

![uniform-min](https://user-images.githubusercontent.com/1934719/39565825-4edbf7dc-4e6e-11e8-9c38-594ec0f5ce2d.png)

**Comment by gergelyke** [comment]
Fixed in https://github.com/godaddy/godaddy.github.io/pull/20

**Comment by chrisvogt** [comment]
Reopening this because the issue I described in the description above is now live in prod. :(

We need to implement consistent card heights to close this ticket.

#### Screenshot

![screen shot 2018-05-04 at 11 00 25 am](https://user-images.githubusercontent.com/1934719/39643697-6b6a968e-4f8a-11e8-8d4f-b8bb571b322e.png)

**Comment by gergelyke** [comment]
Uh, you are right @chrisvogt - should we revert?
